name: CI

# .github/workflows/ci.yml 2025-05-24
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch (or test branch github_ci push)
on:
  push:
    branches: [ master, github_ci ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Install libpng-dev
      run: sudo apt-get install libpng-dev

    - name: Install locale
      shell: bash
      run: sudo locale-gen de_DE.UTF-8 && sudo update-locale

    - name: Install Qt5
      uses: jurplel/install-qt-action@v4
      with:
        version: 5.15.2
        dir: .

    - name: Create Build Environment
      shell: bash
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE} && cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      shell: bash
      run: CMAKE_PREFIX_PATH=$QT_ROOT_DIR cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZINT_TEST=ON -DZINT_STATIC=ON

    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . -j8 --config $BUILD_TYPE

    - name: Test
      working-directory: build
      shell: bash
      run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$(pwd)/backend" PATH=$PATH:"$(pwd)/frontend" QT_QPA_PLATFORM=offscreen ctest -V -C $BUILD_TYPE

  build-ubuntu-debug:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Debug

    steps:
    - uses: actions/checkout@v4

    - name: Install libpng-dev
      run: sudo apt-get install libpng-dev

    - name: Install locale
      shell: bash
      run: sudo locale-gen de_DE.UTF-8 && sudo update-locale

    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9.0
        dir: .

    - name: Create Build Environment
      shell: bash
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE} && cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      shell: bash
      run: CMAKE_PREFIX_PATH=$QT_ROOT_DIR cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZINT_TEST=ON -DZINT_STATIC=ON -DZINT_QT6=ON

    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . -j8 --config $BUILD_TYPE

    - name: Test
      working-directory: build
      shell: bash
      run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$(pwd)/backend" PATH=$PATH:"$(pwd)/frontend" QT_QPA_PLATFORM=offscreen ctest -V -C $BUILD_TYPE

  build-windows-32bit:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE} && cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -A Win32 -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZINT_TEST=ON -DZINT_STATIC=ON -DZINT_USE_PNG=OFF -DZINT_USE_QT=OFF

    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . -j8 --config $BUILD_TYPE

    - name: Test
      working-directory: build
      shell: bash
      run: PATH=$PATH:"$(pwd)/backend/Release:$(pwd)/frontend/Release" ctest -V -C $BUILD_TYPE

  build-windows-64bit:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE} && cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZINT_TEST=ON -DZINT_STATIC=ON -DZINT_USE_PNG=OFF -DZINT_USE_QT=OFF

    - name: Build
      working-directory: build
      shell: bash
      run: cmake --build . -j8 --config $BUILD_TYPE

    - name: Test
      working-directory: build
      shell: bash
      run: PATH=$PATH:"$(pwd)/backend/Release:$(pwd)/frontend/Release" ctest -V -C $BUILD_TYPE

  build-macOS:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE} && cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZINT_TEST=ON -DZINT_STATIC=ON -DZINT_USE_PNG=OFF -DZINT_USE_QT=OFF

    - name: Build
      working-directory: build
      shell: bash
      run: SDKROOT="$(xcrun --sdk macosx --show-sdk-path)" cmake --build . -j8 --config $BUILD_TYPE

    - name: Test
      working-directory: build
      shell: bash
      run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$(pwd)/backend" PATH=$PATH:"$(pwd)/frontend" ctest -V -C $BUILD_TYPE

  build-macOS-sanitize:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      shell: bash
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE} && cmake -E make_directory build

    - name: Configure CMake
      working-directory: build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZINT_TEST=ON -DZINT_SANITIZE=ON -DZINT_USE_PNG=OFF -DZINT_USE_QT=OFF

    - name: Build
      working-directory: build
      shell: bash
      run: SDKROOT="$(xcrun --sdk macosx --show-sdk-path)" cmake --build . -j8 --config $BUILD_TYPE

    - name: Test
      working-directory: build
      shell: bash
      run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$(pwd)/backend" PATH=$PATH:"$(pwd)/frontend" ctest -V -C $BUILD_TYPE
